import { Bb26 } from '../../lib'

interface County {
  county: string
  codes: string[]
}

const counties: County[] = [
  { county: 'Adams', codes: ['ad', 'ae'] },
  { county: 'Alcorn', codes: ['al', 'ac'] },
  { county: 'Amite', codes: ['am'] },
  { county: 'Attala', codes: ['at', 'aa'] },
  { county: 'Benton', codes: ['be'] },
  { county: 'Bolivar', codes: ['br', 'bv', 'bl'] },
  { county: 'Calhoun', codes: ['ca', 'cn'] },
  { county: 'Carroll', codes: ['cr'] },
  { county: 'Chickasaw', codes: ['ch'] },
  { county: 'Choctaw', codes: ['ct'] },
  { county: 'Claiborne', codes: ['cb'] },
  { county: 'Clarke', codes: ['ck', 'cl'] },
  { county: 'Clay', codes: ['cy'] },
  { county: 'Coahoma', codes: ['cm'] },
  { county: 'Copiah', codes: ['cp', 'cq'] },
  { county: 'Covington', codes: ['cv', 'cw'] },
  { county: 'DeSoto', codes: Bb26.range({ start: 'da', end: 'ea' }) },
  { county: 'Forrest', codes: Bb26.range({ start: 'fr', end: 'fv' }) },
  { county: 'Franklin', codes: ['fn'] },
  { county: 'George', codes: ['ge', 'gf'] },
  { county: 'Grenada', codes: ['gn', 'ga'] },
  { county: 'Hancock', codes: Bb26.range({ start: 'ka', end: 'ke' }) },
  { county: 'Harrison', codes: Bb26.range({ start: 'ha', end: 'hl' }) },
  { county: 'Hinds', codes: Bb26.range({ start: 'hn', end: 'ia' }) },
  { county: 'Holmes', codes: ['hl'] },
  { county: 'Humphreys', codes: ['hm'] },
  { county: 'Issaquena', codes: ['is'] },
  { county: 'Itawamba', codes: ['it', 'iw'] },
  { county: 'Jackson', codes: Bb26.range({ start: 'jg', end: 'jn' }) },
  { county: 'Jasper', codes: ['ja', 'jb'] },
  { county: 'Jefferson', codes: ['jf'] },
  { county: 'Jefferson Davis', codes: ['jd'] },
  { county: 'Jones', codes: ['jn', 'jp', 'jq', 'jr'], },
  { county: 'Kemper', codes: ['km'] },
  { county: 'Lafayette', codes: Bb26.range({ start: 'lx', end: 'ma' }) },
  { county: 'Lamar', codes: Bb26.range({ start: 'll', end: 'lo' }) },
  { county: 'Lauderdale', codes: Bb26.range({ start: 'la', end: 'le' }) },
  { county: 'Lawrence', codes: ['lw'] },
  { county: 'Leake', codes: ['lj', 'lk'] },
  { county: 'Lee', codes: Bb26.range({ start: 'le', end: 'li' }) },
  { county: 'Leflore', codes: ['lr', 'ls'] },
  { county: 'Lincoln', codes: ['li', 'lp', 'lq'] },
  { county: 'Lowndes', codes: Bb26.range({ start: 'lt', end: 'lw' }) },
  { county: 'Madison', codes: Bb26.range({ start: 'ma', end: 'mg' }) },
  { county: 'Marion', codes: ['mn', 'mp'] },
  { county: 'Marshall', codes: Bb26.range({ start: 'mq', end: 'mt' }) },
  { county: 'Monroe', codes: Bb26.range({ start: 'mj', end: 'mm' }) },
  { county: 'Montgomery', codes: ['mt'] },
  { county: 'Neshoba', codes: ['ne', 'nf'] },
  { county: 'Newton', codes: ['nv', 'nw'] },
  { county: 'Noxubee', codes: ['nx'] },
  { county: 'Oktibbeha', codes: ['kt', 'ku'] },
  { county: 'Panola', codes: ['pa', 'pb', 'pc'] },
  { county: 'Pearl River', codes: Bb26.range({ start: 'pr', end: 'pv' }) },
  { county: 'Perry', codes: ['pe'] },
  { county: 'Pike', codes: Bb26.range({ start: 'pk', end: 'pn' }) },
  { county: 'Pontotoc', codes: ['pn', 'pp', 'pq'] },
  { county: 'Prentiss', codes: ['pw', 'px'] },
  { county: 'Rankin', codes: Bb26.range({ start: 'ra', end: 'sa' }) },
  { county: 'Scott', codes: ['sc', 'sd'] },
  { county: 'Sharkey', codes: ['sh'] },
  { county: 'Simpson', codes: ['sp', 'sr'] },
  { county: 'Smith', codes: ['sm', 'sn'] },
  { county: 'Stone', codes: ['st', 'su'] },
  { county: 'Sunflower', codes: ['sf', 'sg'] },
  { county: 'Tallahatchie', codes: ['tl'] },
  { county: 'Tate', codes: ['ta', 'tb'] },
  { county: 'Tippah', codes: ['tp', 'tq'] },
  { county: 'Tishomingo', codes: ['ts', 'tt'] },
  { county: 'Tunica', codes: ['tn'] },
  { county: 'Union', codes: ['un', 'up'] },
  { county: 'Walthall', codes: ['wl', 'wm'] },
  { county: 'Warren', codes: Bb26.range({ start: 'wa', end: 'we' }) },
  { county: 'Washington', codes: Bb26.range({ start: 'ws', end: 'wx' }) },
  { county: 'Wayne', codes: ['wy', 'wz'] },
  { county: 'Webster', codes: ['we'] },
  { county: 'Wilkinson', codes: ['wk'] },
  { county: 'Winston', codes: ['wn', 'wp'] },
  { county: 'Yalobusha', codes: ['yl'] },
  { county: 'Yazoo', codes: ['yz', 'ya'] },
]

export default counties
